### ISSUE TITLE
Display loading screens until content is loaded in

### ISSUE THREAD

**Issue by cole-k** [GiselleSerate/suitelife#51]
As of right now, we rely on the speed of both our connection to Firebase and Firebase's response. In reality, connections are not so stable, and we will have issues with, for example, unwrapping optional types which are actually `nil` if we think that Firebase will always be quick to respond.

To fix, we'd have to figure out how to add an animation or some sort of transition as we load in the files, and then resolve that once the callback is returned.

**Comment by cole-k** [comment]
Present an [Activity Indicator](https://developer.apple.com/documentation/uikit/uiactivityindicatorview) until the content has loaded.

**Comment by GiselleSerate** [comment]
Leaving as alert for now.
