### ISSUE TITLE
Sign in window still drawn behind root view controller

### ISSUE THREAD

**Issue by cole-k** [GiselleSerate/suitelife#6]
You can see the sign in window if you swipe all the way to the left or right in the list tab, which is evidence of the fact that it isn't completely removed from the view.

Quick fixes would be to configure the look of the controller depending on whether the user is signed in or not (if the user is signed in, hide the button and labels and change the background to whatever color we want the background to be -- probably white). See Google's example

    $ pod try Google
    $ 2              # to try the sign-in example

for how to do this hiding; it relies on methods of `GIDSignInUIDelegate` if memory serves.

**Comment by GiselleSerate** [comment]
Not sure when this got resolved, but it appears to be resolved.

**Comment by GiselleSerate** [comment]
definitely NOT resolved
